version: "2"

run:
  timeout: 5m
  tests: true

linters:
  enable:
    - govet
    - ineffassign
    - unused
    - misspell
    - staticcheck
  settings:
    staticcheck:
      checks:
        - "all"
        - "-SA1012"  # nil context in tests
        - "-SA4017"  # return value ignored
        - "-SA9003"  # empty branch
        - "-S1009"   # nil check before len
        - "-ST1000"  # package comment
        - "-ST1003"  # underscore naming (Terraform convention)
        - "-ST1020"  # comment format
        - "-QF1001"  # De Morgan's law
        - "-QF1003"  # tagged switch

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
