version: "2"

run:
  timeout: 5m
  tests: true

linters:
  enable:
    - govet
    - ineffassign
    - unused
    - misspell
    - staticcheck
    - errcheck
    - gosec
    - nilerr         # Detect returning nil when error is not nil
    - unconvert      # Remove unnecessary type conversions
    - predeclared    # Find shadowed predeclared identifiers
    - errorlint      # Error handling best practices (Go 1.13+)
    - durationcheck  # Check for duration multiplication issues
    - nosprintfhostport # Check for misuse of Sprintf for host:port
    - dupword        # Check for duplicate words in comments
    - copyloopvar    # Detect unnecessary loop variable copies (Go 1.22+)
    - gocritic       # Style and performance checks (ifElseChain, dupBranchBody, etc.)
    # Note: whitespace linter disabled - conflicts with multi-line HCL strings in test files
    # Note: bodyclose is not enabled because it doesn't recognize helper functions
    # like utils.CloseResponseBody(). The code correctly closes HTTP response bodies
    # using defer utils.CloseResponseBody(httpResp) after each API call.
  settings:
    staticcheck:
      checks:
        - "all"
        - "-SA1012"  # nil context in tests
        - "-SA4017"  # return value ignored
        - "-SA9003"  # empty branch
        - "-S1009"   # nil check before len
        - "-ST1000"  # package comment
        - "-ST1003"  # underscore naming (Terraform convention)
        - "-ST1020"  # comment format
        - "-QF1001"  # De Morgan's law
        - "-QF1003"  # tagged switch

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
