run:
  timeout: 5m
  tests: true

linters:
  enable:
    - govet
    - revive
    - staticcheck
    - errcheck
    - gosimple
    - ineffassign
    - typecheck
    - unused
    - misspell
    - goconst
    - gosec

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  new: true

revive:
  rules:
    - name: exports
    - name: if-return
    - name: indent-error-flow
    - name: var-declaration
    - name: unused-parameter
    - name: banned-characters
    - name: confusing-naming
    - name: dot-imports
